CRIMRE-118 Use datastore for search filter
ministryofjustice/laa-review-criminal-legal-aid pull request #75
Opened 2023-01-03 11:59 UTC by timpeat

## Description of change

## Link to relevant ticket
[CRIMRE-118](https://dsdmoj.atlassian.net/browse/CRIMRE-118)
[CRIMRE-83](https://dsdmoj.atlassian.net/browse/CRIMRE-83)

## Notes for reviewer
Completes 83 as well as refactors previous search/filter tickets to use the datastore.

## Screenshots of changes (if applicable)

### Before changes:

### After changes:

## How to manually test the feature

2023-01-03 13:54 UTC, timpeat reviewed
Get next using datastore search to follow.

2023-01-03 15:06 UTC, willmcb requested changes
👍 few small comments.

2023-01-03 15:06 UTC, willmcb commented on spec/system/get_next_application_spec.rb
> +      3.times do
This is stubbed now with en empty response - so no need for 3.times

2023-01-03 15:06 UTC, willmcb commented on spec/system/search_applications/filter_by_caseworker_spec.rb
> +    it 'can choose from "", "Unnassigned", "All assigned", and caseworkers' do
Extra 'n' in Unassigned

2023-01-04 10:35 UTC, timpeat commented on app/lib/types.rb
> +  DateTime = DateTime | JSON::DateTime
Requires PR namespace  Types in LaaCrimeSchemas. Will do separately.

2023-01-04 10:36 UTC, timpeat commented on app/models/application_search_filter.rb
> +    users = User.where(
done

2023-01-04 11:06 UTC, timpeat commented on app/models/application_search_result.rb
> +  def days_passed
Ticket added to backlog.

2023-01-04 11:31 UTC, timpeat reviewed
@arthurashman @willmcb Ready for another review.

2023-01-04 14:01 UTC, willmcb approved these changes
👍

2023-01-04 14:02 UTC, merged